#!/bin/bash

cd $(dirname $0)/..

docker build -t niusmallnan/k3cos:latest .

docker run -it --rm -v $PWD:/build \
    -v /var/run/docker.sock:/var/run/docker.sock \
    quay.io/costoolkit/elemental-cli:v0.2.5 build-iso \
    --local --config-dir build/ -o build/ niusmallnan/k3cos:latest
