name: "Rootfs Layout Settings"
stages:
  # Setup persistency so k3s works properly
  # See also: https://rancher.github.io/elemental-toolkit/docs/reference/immutable_rootfs/#configuration-with-an-environment-file
  rootfs:
  - name: "Immutable Layout configuration"
    environment_file: /run/cos/cos-layout.env
    environment:
      VOLUMES: "LABEL=COS_OEM:/oem LABEL=COS_PERSISTENT:/usr/local"
      OVERLAY: "tmpfs:25%"
      RW_PATHS: "/var /etc /srv"
      PERSISTENT_STATE_PATHS: >-
        /etc/systemd
        /etc/rancher
        /etc/ssh
        /etc/iscsi
        /etc/cni
        /home
        /opt
        /root
        /usr/libexec
        /var/lib/wicked
        /var/log
        /var/lib/rancher
        /var/lib/kubelet
        /var/lib/NetworkManager
        /var/lib/longhorn
        /var/lib/cni
      PERSISTENT_STATE_BIND: "true"
  initramfs:
  - if: '[ ! -f "/run/cos/recovery_mode" ]'
    name: "Persist /etc/machine-id"
    commands:
    - |
      # persist machine-id
      if [ -s /usr/local/etc/machine-id ]; then
        cat /usr/local/etc/machine-id > /etc/machine-id
      else
        mkdir -p /usr/local/etc
        cp /etc/machine-id /usr/local/etc
      fi
